# Load libraries and data
```{r}
library(dplyr)
library(ggplot2)

# Zeale
sampsZ <- read.csv("data/sampnames.csv") %>%
  mutate(s1 = substr(samp,7,100),
         s = gsub(x = s1, pattern = ".ali.cut.n21n.fasta", replacement = "")) %>%
  select(-s1) %>%
  mutate(tags = "aaaaa:ttttt",
         fwd = "AGATATTGGAACWTTATATTTTATTTTTGG",
         rev = "WACTAATCAATTWCCAAATCCTCC",
         exp = "Z") %>%
  select(exp, s, tags, fwd, rev, samp)

# Coleop
sampsC <- read.csv("data/sampnames.csv") %>%
  mutate(s1 = substr(samp,7,100),
         s = gsub(x = s1, pattern = ".ali.cut.n21n.fasta", replacement = "")) %>%
  select(-s1) %>%
  mutate(tags = "aaaaa:ttttt",
         fwd = "TGCAAAGGTAGCATAATMATTAG",
         rev = "TCCATAGGGTCTTCTCGTC",
         exp = "C") %>%
  select(exp, s, tags, fwd, rev, samp)

```

# create BASH scripts to add fake tags to sequences
```{r}

s <- sampsZ$s

# make scripts
for (i in s) {

prefix = substr(sampsZ[sampsZ$s==i,]$samp, 1, 6)
  
cat(paste0("#!/bin/bash

#SBATCH --partition=main
#SBATCH --requeue
#SBATCH --job-name=index",i, "
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=80000
#SBATCH --time=3-00:00:00
#SBATCH --output=slurm.justr.%N.%j.out
#SBATCH --error=slurm.justr.%N.%j.err

sed '/^>/ !{s/^/aaaaa/; s/$/aaaaa/}' ", prefix, i, ".ali.cut.n21n.fasta > ", i, ".ali.cut.n21n.tag.fasta
"),
file = paste0("data/",prefix,"index",i,".sh")
)
}
```

# make text file inputs to ngsfilter
```{r}

# Zeale
for (i in 1:nrow(sampsZ)){
prefix = substr(sampsZ[i,]$samp, 1, 6)

write.table(sampsZ[i,1:5], row.names = F, col.names = F, 
            file = paste0("data/",prefix, sampsZ[i,2],"indexZ.txt"), quote = F)
}

# Coleop
for (i in 1:nrow(sampsC)){
prefix = substr(sampsC[i,]$samp, 1, 6)

write.table(sampsC[i,1:5], row.names = F, col.names = F, 
            file = paste0("data/",prefix, sampsC[i,2],"indexC.txt"), quote = F)
}
```

# make bash scripts to run ngsfilter sample by sample
```{r}
# Zeale
s <- sampsZ$s

# make scripts
for (i in s) {
prefix = substr(sampsZ[sampsZ$s==i,]$samp, 1, 6)
  
cat(paste0("#!/bin/bash

#SBATCH --partition=main
#SBATCH --requeue
#SBATCH --job-name=ngsfiltZ
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=80000
#SBATCH --time=3-00:00:00
#SBATCH --output=slurm.justr.%N.%j.out
#SBATCH --error=slurm.justr.%N.%j.err

ngsfilter -t ",prefix,i,"indexZ.txt -u unidentified",i,".Z.fasta ",i,".ali.cut.n21n.tag.fasta > \\
  ",i,".ali.cut.n21n.tag.ngs.Z.fasta
"),
file = paste0("data/", prefix, "ngs",i,".Z.sh"))
}

# Coleop
s <- sampsC$s

# make scripts
for (i in s) {
prefix = substr(sampsC[sampsC$s==i,]$samp, 1, 6)

cat(paste0("#!/bin/bash

#SBATCH --partition=main
#SBATCH --requeue
#SBATCH --job-name=ngsfiltC
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=80000
#SBATCH --time=3-00:00:00
#SBATCH --output=slurm.justr.%N.%j.out
#SBATCH --error=slurm.justr.%N.%j.err

ngsfilter -t ",prefix,i,"indexC.txt -u unidentified",i,".C.fasta ",i,".ali.cut.n21n.tag.fasta > \\
  ",i,".ali.cut.n21n.tag.ngs.C.fasta
"),
file = paste0("data/", prefix,"ngs",i,".C.sh"))
}
```